- contracts/Forc.toml
Updating 'Forc.toml' to use `authors` instead of `author`. This enables compatibility with the change being made in this PR https://github.com/FuelLabs/sway/pull/822
> change author to authors in Forc.toml

- .github/workflows/gh-pages.yml
- client/package.json
- client/src/index.tsx
- Add GitHub action to build source code from client folder and commit to `gh-pages` branch.
- 🚨 Github doesn't support SPA, but it's possible to achieve functionality by adding a `404.html` file, an exact copy from the `index.html`. The only issue with the solution is returned status code instead of being `200` is `404`.
closes: #16
> feat: deploy client app to gh-pages

- client/src/pages/MintToken.tsx
- client/src/types/contracts/TokenContractAbi.d.ts
- client/src/types/contracts/factories/TokenContractAbi__factory.ts
- contracts/swayswap_contract/Forc.lock
- contracts/swayswap_contract/src/main.sw
- contracts/swayswap_contract/tests/harness.rs
- contracts/token_abi/src/main.sw
- contracts/token_contract/Forc.lock
- contracts/token_contract/src/main.sw
With `forc 0.10.3`, single argument contract methods work as expected. We can now use the new storage syntax as well, at least for the total LP token supply.
> Use new storage syntax and remove unnecessary arguments

- client/src/pages/Pool.tsx
I have implemented a temporary solution using `transformRequest`, fixing the balance increase during the creation of a pool.
Refs.: https://github.com/FuelLabs/fuels-ts/issues/229
> fix: remove duplicated inputs

- .github/workflows/gh-pages.yml
- Change from release `swayswap` from `push to master` to `published a release`
> ci: deploy page when a release is published

- .github/workflows/gh-pages.yml
- client/deploy-contracts/index.ts
- client/package.json
- client/src/components/CoinInput.tsx
- client/src/config.ts
- client/src/pages/MintTokenPage.tsx
- client/src/pages/PoolPage.tsx
- client/src/pages/RemoveLiquidityPage.tsx
- client/src/pages/SwapPage.tsx
- client/src/types/contracts/SwayswapContractAbi.d.ts
- client/src/types/contracts/TokenContractAbi.d.ts
- client/src/types/contracts/factories/SwayswapContractAbi__factory.ts
- client/yarn.lock
- contracts/swayswap_abi/src/main.sw
- contracts/swayswap_contract/Forc.lock
- contracts/swayswap_contract/src/main.sw
- contracts/token_contract/Forc.lock
- docker/fuel-core/Dockerfile
- docker/fuel-core/chainConfig.json
This PR fixes swap with minimum and maximum. We had an issue when simulating max/min amounts we pass the value as a param to the method. But on `swap` execution the value is `forwarded` changing the result of `this_balance` and also the calculations of `get_input_price` and `get_output_price`.
[feat: change fee calculation for swap](https://github.com/FuelLabs/swayswap/pull/81/commits/5ab31dc0022b90a7df8c8670f9c96f870684ff06)
- We change fee calculation from using multiplication of numbers to `1000` and `997`. To a fee price approximation using the `amount` divided by `333`. Ex.: `1_000_000_000/333 = 3003003` that is near of `3000000`.
[chore: reduce decimal numbers to 3](https://github.com/FuelLabs/swayswap/pull/81/commits/51d4d1300242d784b72755b90513e4d4bc8fd69f)
- Reduce to 3 decimals …
> fix: swap get values

- contracts/swayswap_contract/src/main.sw
closes https://github.com/FuelLabs/swayswap/issues/80
> Minor cleanup

- client/src/components/CoinSelector.tsx
- client/src/components/CoinsListDialog.tsx
- client/src/hooks/useAssets.ts
Fix `URL` of icons to use `BASE_URL`
> fix: update icons url

- packages/app/package.json
- packages/app/src/App.tsx
- packages/app/src/context/AppContext.tsx
- packages/app/src/lib/recoilEffects.ts
- pnpm-lock.yaml
✨ Fix #165 
This pull request intends to remove Recoil since we are using Jotai now as state management.
> 👉🏻 After this pull request, you need to remove local storage and create a wallet again.
@LuizAsFight @luizstacio
> refac: remove recoil and use jotai instead

- packages/app/src/components/CoinInput.tsx
- packages/app/src/config.ts
- packages/app/src/lib/asset.ts
- packages/app/src/pages/PoolPage/AddLiquidity.tsx
- When set one token value, calculate the other one according to `reserve ratio` we have
- Validate `add_liquidity` ratio is right
Closes #179
Closes #148
> feat(PoolPage): When set input value, calculate the other input value. Validate if pool ratio is right

- packages/app/src/pages/PoolPage/AddLiquidity.tsx
- packages/app/src/types/contracts/index.ts
Button
- show `Add Liquidity` when there's already a pool
- show `Create Liquidity` when there's not a pool yet
After create a pool
- reload `balance`
- reload `poolInfo`
- clear both `inputs`
Closes #180
> feat(PoolPage): improve button feedback. reload/clear after create liquidity

- packages/app/package.json
- packages/app/src/config.ts
- packages/app/src/lib/utils.ts
- packages/app/src/pages/SwapPage/PricePerToken.tsx
- packages/app/src/pages/SwapPage/SwapComponent.tsx
- packages/app/src/pages/SwapPage/index.tsx
- packages/app/src/pages/SwapPage/types.ts
- pnpm-lock.yaml
- Fixes price calculation per token on the preview. Ref.: #126 
- Add validation states to guide users throw the flow. Closes: #132
> feat: add user guided states on swap

- .github/workflows/pr.yaml
- README.md
- packages/app/README.md
Since we are generating changelogs based on conventional commits, when we are squashing pull requests without the right title we are lost a lot of information when generating our changelogs.
This pull request just adds a Github action that validates the title according to conventional commits and also checks lint and tests.
> ci: add action for validate pull request

- packages/app/src/pages/PoolPage/AddLiquidity.tsx
- User won't get stuck when there's any error
- Show general feedback message + send user back to initial stage of PoolPage
- Improve success / error feedback message
Closes #141
> fix(PoolPage): handle error feedback (getting stuck in Provide Liquidity stage)

- packages/app/.env.production
Due to issues with cache and bad management of env variables on vercel. We should add .env file on the repo.
> fix: add prod env variables due to vercel issues

- contracts/exchange_abi/src/main.sw
- contracts/exchange_contract/src/main.sw
- packages/app/.env.production
- packages/app/src/config.ts
- packages/app/src/hooks/useAddLiquidity.ts
- packages/app/src/pages/PoolPage/AddLiquidity.tsx
- packages/app/src/pages/PoolPage/PoolsPreview.tsx
- packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
- packages/app/src/pages/PoolPage/index.tsx
- packages/app/src/types/contracts/Exchange_contractAbi.d.ts
- packages/app/src/types/contracts/factories/Exchange_contractAbi__factory.ts
- contract changes
- add_liquidity
- use always contract user balance, instead of front-end value
- if tokens ratio is wrong, contract won't break anymore. Instead we return the previous depositted user balances to his wallet
- if tokens ratio is ok, should return any leftover token to user wallet
- get_balance
- return user contract balance, instead of whole contract balance
- frontend changes
- PoolPage - Add Liquidity - removed ratio validation from front-end, as contract is already handling it now
- increased deadline to 5000 in remove_liquidity and add_liquidity
- created config param for contracts Deadline
Closes #200
> fix(PoolPage): improve add_liquidity contract

- packages/app/src/hooks/useEthBalance.ts
- packages/app/src/hooks/useUserPositions.tsx
- packages/app/src/lib/utils.ts
- packages/app/src/pages/PoolPage/AddLiquidity.tsx
- packages/app/src/pages/PoolPage/AddLiquidityPoolPrice.tsx
- packages/app/src/pages/PoolPage/AddLiquidityPreview.tsx
- packages/app/src/pages/PoolPage/PoolCurrentPosition.tsx
- packages/app/src/pages/PoolPage/PoolCurrentReserves.tsx
- packages/app/src/pages/PoolPage/Pools.tsx
- packages/app/src/pages/PoolPage/RemoveLiquidityPreview.tsx
- packages/app/src/pages/PoolPage/usePreviewAddLiquidity.ts
- packages/app/src/pages/PoolPage/usePreviewRemoveLiquidity.ts
`Add Liquidity Page`
- removed old `reserves` box
- added `Preview` info
- added new `Current Pool Reserves` info
- format with thousand and decimal separators (make sure show some big numbers better)
- refact in page components structure
Closes #219 
Closes #220
> feat(AddLiquidityPage): add preview + current pool reserves

- .gitignore
- packages/app/.gitignore
- packages/app/cypress/e2e/App.cy.ts
- packages/app/cypress/support/commands.ts
- packages/app/cypress/support/index.d.ts
- packages/app/src/styles/components/coin-balance.css
- packages/app/src/styles/components/coin-input.css
- packages/app/src/styles/components/coin-selector.css
- packages/app/src/styles/index.css
- packages/app/src/systems/Core/components/AssetItem.tsx
- packages/app/src/systems/Core/components/CoinBalance.tsx
- packages/app/src/systems/Core/components/CoinInput.tsx
- packages/app/src/systems/Core/components/CoinSelector.tsx
- packages/app/src/systems/Pool/components/AddLiquidityPoolPrice.tsx
- packages/app/src/systems/Pool/components/AddLiquidityPreview.tsx
- packages/app/src/systems/Pool/components/PoolCurrentPosition.tsx
- packages/app/src/systems/Pool/components/RemoveLiquidityPreview.tsx
- packages/app/src/systems/Pool/pages/AddLiquidity.tsx
- packages/app/src/systems/Pool/pages/RemoveLiquidity.tsx
- packages/app/src/systems/Swap/components/SwapComponent.tsx
- packages/app/src/systems/Swap/components/SwapPreview.tsx
- Created `CoinBalance` component from `CoinSelector` to centralize balance behavior in a different line and fix the layout bug.
> fix: coin input value being cut by bottom line balance

- packages/app/src/systems/Core/components/CoinInput.tsx
- packages/app/src/systems/Pool/pages/AddLiquidity.test.tsx
- addressed bug when typing only "." in the coin input
- created unit test to make sure it's working on the way it's supposed to
Closes #287
> fix: correct behavior when typing only "." in the coin input

- packages/app/src/styles/components/welcome-page.css
> fix: reduce images on mobile

- packages/app/src/systems/Home/components/Header.tsx
The docs are for developers, not users, and they're already readily linked-to in the GitHub repo.
Reported by @Braqzen
> chore: remove redundant docs link in header

- packages/app/src/systems/Home/components/HomeHero.tsx
Fixes #323
Note that this only functionally removes the button, it doesn't change the padding. Therefore, the text looks a bit low. This can be fixed in a subsequent PR (tracked in #326).
> chore: remove launch app button on home

- packages/app/src/systems/Home/components/HomeHero.tsx
Reverts FuelLabs/swayswap#325
The change wasn't objectively better, so in the interest of avoiding bikeshedding, just reverting it.
> chore: Revert "chore: remove launch app button on home"

- packages/app/src/systems/Core/utils/queryClient.tsx
Avoid multiple error notifications using block `msg` as ID of the toast. On this way we only show again if the block `msg` is different.
Closes #334
> feat: avoid multiple error notifications

- packages/app/src/styles/components/button.css
- packages/app/src/styles/components/home-page.css
- packages/app/src/styles/components/welcome-page.css
- packages/app/src/systems/Core/components/CoinInput.tsx
- packages/app/src/systems/Core/components/TokenIcon.tsx
- packages/app/src/systems/Faucet/components/FaucetApp.tsx
- packages/app/src/systems/Home/components/Header.tsx
- packages/app/src/systems/UI/components/InvertButton.tsx
- packages/app/src/systems/Welcome/components/CreateWallet.tsx
- packages/app/src/systems/Welcome/components/WelcomeDone.tsx
Fixes app to work on safari iOS version 14~15.
The biggest problem was related to the use of the late spaces of CSS, which supports some features from layout `grid` and `flex` together.
- Fix iOS version 14~15
- Add `inputMode` on `CoinInput` to show correct keyboard on mobile.
cc: @SilentCicero
> fix: change css to be compatible with safari on ios 14

- packages/app/src/systems/Core/components/CoinBalance.tsx
make CoinBalance have a fixed height, to show the same size even when has no balance for that specific coin. Avoiding layout flicks and moving elements
Closes #363
> chore: keep input size when has no balance

- packages/app/src/systems/Swap/machines/swapMachine.ts
When fill coin "from" value before selecting "To" token, swap preview should be calculated after selecting the "To" token (DAI)
https://user-images.githubusercontent.com/8636507/177417901-910b96d0-6a86-49fe-b264-bc490e7e4dd0.mov
Closes #356
> feat: should set input value when has no coin input too

- packages/app/src/systems/Core/components/CoinBalance.tsx
- packages/app/src/systems/Swap/hooks/useSwapMaxButton.tsx
- packages/app/src/systems/Swap/pages/SwapPage.test.tsx
In Swap page, stop hiding max button, only disable instead.
Now when we refresh the page, there's no blinking in the "max" button, making it look smoother
https://user-images.githubusercontent.com/8636507/177425354-e68ecadd-7054-4f8d-816b-e942a1a49a4d.mov
Closes #362
> feat: should disable max button instead of hiding

- .github/workflows/gh-pages.yml
- .github/workflows/pr.yaml
- .vscode/settings.json
- README.md
Add note to drop support support for swayswap for latest fuel-core versions.
> chore: remove support for SwaySwap
