FuelLabs/swayswap

client/package.json, client/yarn.lock
`yarn install --frozen-lockfile` on the CI, was not working properly. I had to update the fuels version to fix it. On local `yarn install --frozen-lockfile` was working correctly.
=> chore: update fuels version

contracts/Forc.lock, contracts/src/main.sw
As per https://github.com/Uniswap/v1-contracts/blob/c10c08d81d6114f694baa8bd32f555a40f6264da/contracts/uniswap_exchange.vy#L57
=> Small typo and a change in imports

client/src/pages/MintToken.tsx
=> fix: remove temporary second params #39

.github/workflows/gh-pages.yml, client/package.json, client/yarn.lock
- Add swayswap contract id and token contract id to the CI and update fuels and `typechain-target-fuels` dependencies.
closes: #46
=> feat: add contracts configs to CI and update dependencies

client/src/pages/Pool.tsx
This fixes the pool calls so you can add liquidity and get LP tokens.
Note: the "ETH printing" issue is still around. It looks like it's going to need some external changes so I don't want to block this.
=> Fix Pool Calls

client/package.json, client/scripts/build-contracts.sh, client/yarn.lock, contracts/swayswap_contract/Forc.lock, contracts/token_contract/Forc.lock
- Add command to prettify code
- Update `forc to v0.11`, on code it just updates the `Forc.lock` file, on local the new binaries are working correctly also.
=> chore: command to prettify

.github/workflows/gh-pages.yml, client/yarn.lock
- Update contract id on CI envs
- Update yarn.lock file
=> chore: update swap contract id

client/package.json, client/src/AppRoutes.tsx, client/src/components/Header.tsx, client/src/pages/MintTokenPage.tsx, client/src/pages/PoolPage.tsx, client/src/pages/RemoveLiquidityPage.tsx, client/src/pages/SwapPage.tsx, client/src/pages/WalletPage.tsx, client/src/types/contracts/SwayswapContractAbi.d.ts, client/src/types/contracts/factories/SwayswapContractAbi__factory.ts, client/src/types/pages.ts, client/yarn.lock, contracts/swayswap_abi/src/main.sw, contracts/swayswap_contract/src/main.sw
- Solves the issue of increasing reserves when forwarding coins on a contract call.
- This was fixed to improve UX on preview swap, now it's possible to simulate values even if you don't have enough balance, by not forwarding coins.
closes: #82, #87
=> feat: track reserve amounts on storage

client/src/components/CoinInput.tsx, client/src/config.ts, client/src/context/AppContext.tsx
Improve coin input to be limited to u64 max amount
=> feat: improve coin input max and value validation

client/src/components/InvertButton.tsx
https://user-images.githubusercontent.com/2029172/168933085-f7d8ba77-348b-4503-914e-98c95600dfd1.mov
✨ Just a small animation for invert button
=> refac: add animation on invert button

client/package.json, client/src/components/CoinInput.tsx, client/src/components/CoinSelector.tsx, client/src/index.css, client/src/pages/PoolPage.tsx, client/src/pages/RemoveLiquidityPage.tsx, client/src/pages/SwapPage/SwapComponent.tsx, client/yarn.lock
Just some general style improvements
=> style: small ui details

client/src/pages/PoolPage.tsx
=> Fix from/to range calculations in pool page

client/src/components/CoinInput.tsx, client/src/lib/utils.ts, client/src/pages/SwapPage/index.tsx
- Disable the button if the user do not have a balance
- Enable CoinInput to receive null
=> Check balance amount before swap

.github/workflows/gh-pages.yml, packages/app/scripts/deploy-contracts.sh, packages/app/src/components/PageContent.tsx, packages/app/src/pages/PoolPage/index.tsx
=> style: change pool tabs style

packages/app/package.json, packages/app/src/components/Button.tsx, packages/app/src/components/CoinInput.tsx, packages/app/src/components/NumberInput.tsx, packages/app/src/components/Spinner.tsx, packages/app/src/config.ts, packages/app/src/pages/SwapPage/PricePerToken.tsx, packages/app/src/pages/SwapPage/SwapComponent.tsx, packages/app/src/pages/SwapPage/index.tsx, packages/app/src/pages/SwapPage/jotai.ts, pnpm-lock.yaml
✨ Fix #126, fix #158 and fix #159
=> feat: add price per token feature on swap

README.md, packages/app/README.md
=> docs: update READMEs with getting started and project structure info

README.md
=> docs: info for env variables and setup

packages/app/package.json, packages/app/src/components/Skeleton.tsx, packages/app/src/layouts/MainLayout.tsx, pnpm-lock.yaml
=> refac: add skeleton as loading

packages/app/src/components/Toaster.tsx, packages/app/src/components/WalletWidget.tsx, packages/app/src/hooks/useFaucet.ts, packages/app/src/hooks/useUserInfo.ts, packages/app/src/pages/CreateWallet.tsx
=> feat: auto faucet

packages/app/src/pages/PoolPage/AddLiquidity.tsx
- Add `alert` box to show when a new pool is being created
- Hide `Reserves` box when there's not actual pool yet
https://user-images.githubusercontent.com/8636507/169915163-cb22db75-9611-449d-a78c-ebddcca2d743.mov
Closes #181
=> feat(PoolPage): add feedback alert when creating a new pool

packages/app/src/pages/PoolPage/RemoveLiquidity.tsx
- Show guided message in remove button
- Reload balance after success
- Clear input after success
Closes #175
=> feat(PoolPage): improve button feedback + improve success feedback

packages/app/deploy-contracts/index.ts, packages/app/src/components/ButtonGroup.tsx, packages/app/src/components/Card.tsx, packages/app/src/components/CoinInput.tsx, packages/app/src/components/Header.tsx, packages/app/src/components/Menu.tsx, packages/app/src/components/Popover.tsx, packages/app/src/components/Tooltip.tsx, packages/app/src/hooks/useBalances.ts, packages/app/src/pages/PoolPage/AddLiquidity.tsx, packages/config/eslint.js, packages/test-utils/src/mocks/image.ts, packages/test-utils/src/user-event.ts
=> chore: make use of any type an eslint error

packages/app/src/pages/SwapPage/PricePerToken.tsx, packages/app/src/pages/SwapPage/index.tsx
=> fix: price per token calculation

packages/app/package.json, packages/app/src/components/Card.tsx, packages/app/src/components/CoinInput.tsx, packages/app/src/components/CoinSelector.tsx, packages/app/src/components/FaucetWidget.tsx, packages/app/src/components/Header.tsx, packages/app/src/components/InvertButton.tsx, packages/app/src/components/PreviewTable.tsx, packages/app/src/components/Skeleton.tsx, packages/app/src/components/TokenIcon.tsx, packages/app/src/components/WalletWidget.tsx, packages/app/src/hooks/useBreakpoint.ts, packages/app/src/layouts/MainLayout.tsx, packages/app/src/pages/PoolPage/AddLiquidity.tsx, packages/app/src/pages/PoolPage/AddLiquidityPoolPrice.tsx, packages/app/src/pages/PoolPage/AddLiquidityPreview.tsx, packages/app/src/pages/PoolPage/PoolCurrentReserves.tsx, packages/app/src/pages/SwapPage/SwapComponent.tsx, packages/app/src/pages/SwapPage/SwapPreview.tsx, packages/app/src/pages/SwapPage/index.tsx, packages/app/src/styles/components/card.css, packages/app/src/styles/components/coin-input.css, packages/app/src/styles/components/coin-selector.css, packages/app/src/styles/components/faucet-widget.css, packages/app/src/styles/components/header.css, packages/app/src/styles/components/layout.css, packages/app/src/styles/index.css, pnpm-lock.yaml
=> refactor: mobile navigation and responsive improvements

packages/app/src/components/Card.tsx, packages/app/src/components/NavigateBackButton.tsx, packages/app/src/hooks/useAddLiquidity.ts, packages/app/src/pages/PoolPage/AddLiquidity.tsx, packages/app/src/pages/PoolPage/AddLiquidityPreview.tsx, packages/app/src/pages/PoolPage/Pools.tsx, packages/app/src/pages/PoolPage/RemoveLiquidity.tsx, packages/app/src/styles/components/button.css, packages/app/src/styles/components/layout.css
=> feat: UX fixes

packages/scripts/src/bin/index.ts
fix some previous changes that broke the scripts commands: #160
=> fix: create multiple commands

packages/app/src/styles/components/faucet-widget.css, packages/app/src/styles/components/header.css, packages/app/src/styles/components/main-layout.css, packages/app/src/systems/Core/components/MainLayout.tsx
=> feat: fix header on top and faucet at the bottom

packages/app/src/systems/Core/components/CoinInput.tsx, packages/app/src/systems/Faucet/components/FaucetWidget.tsx, packages/app/src/systems/Home/components/HomeHero.tsx, packages/app/src/systems/Welcome/components/AddFunds.tsx, packages/app/src/systems/Welcome/components/CreateWallet.tsx, packages/app/src/systems/Welcome/components/WelcomeDone.tsx
Just minor typo fixes and wording improvements.
=> chore: minor fixes, typos, etc.

packages/app/src/systems/Core/utils/feedback.tsx
close #312 
Feel free to reject this PR if this change is unnecessary etc.
=> style: bump tx feedback 5s -> 8s

packages/app/src/systems/UI/components/Button.tsx
- Avoid layout moving when button loading size changes.
Closes #332
=> feat: loading button size

packages/app/src/config.ts, packages/app/src/systems/Swap/utils/queries.ts
Temp. fix to deadline issue, will going to fix with dynamic block height on a future PR.
Ref: #340
=> fix: increase deadline

packages/app/cypress/e2e/App.cy.ts, packages/app/src/systems/Core/components/CoinInput.tsx
=> fix: add allow decimals

packages/app/src/systems/Home/components/HomeHero.tsx, packages/app/src/systems/Welcome/components/WelcomeDone.tsx
=> chore: add test network disclaimers

packages/app/src/systems/Core/components/CoinInput.tsx, packages/app/src/systems/Core/hooks/useCoinInputDisplayValue.ts, packages/app/src/systems/Pool/pages/AddLiquidity.test.tsx, packages/app/src/systems/Swap/machines/swapMachine.ts
There are some failing tests in SwapPage.Test.tsx but they are failing on master. No additional regressions have been introduced in this branch.
closes #365; closes #368.
=> fix: stopped recalculation when no value change; fixed debounce on input

.github/workflows/gh-pages.yml, packages/app/package.json, packages/app/src/main.tsx, packages/app/src/systems/Core/components/Header.tsx, packages/app/src/systems/Core/components/MigrationWarning.tsx, pnpm-lock.yaml
=> feat: update contract ids and add migration warning

packages/app/src/systems/Swap/machines/swapMachine.ts, packages/app/src/systems/Swap/utils/helpers.ts
=> fix: erase zeros should not clean the input

packages/app/src/systems/Faucet/components/FaucetApp.tsx, packages/app/src/systems/Faucet/hooks/useFaucet.ts
=> fix: show faucet return error and reset captcha
